### ISSUE TITLE
Feature Request: Config for Tank Capacity

### ISSUE THREAD

**Issue by PiggyWhiskey** [nicolas-lang/Factorio.LongStorageTanks#4]
Request a Config option for configurable Tank Sizes

Current Capacity is 80k for a 2-slot Tank.
My modded fluid wagons carry 150k fluid per wagon

This means I need to stagger/alternate several of these wagons to functionally use them.

**Comment by Foeglas** [comment]
Configurable capacity would also help with dynamic limits and stackers. Say I have only one physical stop for 4-wagon trains (100k capacity) and multiple stacker slots to support 500k/minute consumption. But the 4-wagon length tank only holds 160k, which is less than 2 full train buffers. Pressurized Fluids feels like too powerful of a workaround for tank capacity because it can just as easily fill the train.

**Comment by nicolas-lang** [comment]
makes sense, I'll have a look when I work on the mod again.

**Comment by nicolas-lang** [comment]
These startup settings are avaliable and shoudl cover your issues:
![image](https://github.com/user-attachments/assets/1b2a0ec4-8bc0-4c70-9249-2054645f3715)

please play around with them and re-open this feature request if you have additional wishes.
